media_type:
  - type: 'phone call'
    description: |
      A real-time verbal interaction between the customer and service agent, where all communication is conveyed solely through voice without any visual or textual support. 
      The success of the conversation depends on **clear articulation, tone modulation, and active listening**.

      **Characteristics**:
        - No visual cues: Tone, pacing, and verbal emphasis replace body language and facial expressions.
        - Immediate feedback loop: Requires **quick responses** and tone adjustments based on customer emotions and urgency.
        - High engagement: Unlike text-based channels, the agent must actively **maintain the customer’s attention**.
        - Risk of miscommunication: Without written records, **precise wording and summarization** are critical.
        - No lists, bullet points or enumerations are possible.

      **Guidelines**:
        - Speak **clearly and at a steady pace** to ensure customer comprehension.
        - **Acknowledge concerns verbally** (e.g., "I understand your frustration, let me check that for you").
        - Avoid long silences—if you need time to find information, **keep the customer informed**.

  - type: 'live chat'
    description: |
      A **real-time text-based conversation** where messages are exchanged rapidly. The interaction should mimic the natural flow of a verbal conversation while being concise and efficient.

      **Characteristics**:
        - Fast-paced: Customers expect **quick responses** and minimal waiting time.
        - Concise and direct: Unlike emails, messages should be **short and easy to digest**.
        - Semi-formal: Communication should be **friendly yet professional**, avoiding excessive formalities.
        - Multi-tasking: Agents often handle **multiple conversations simultaneously**, requiring efficiency.

      **Guidelines**:
        - **Respond quickly** to acknowledge the customer’s message before crafting a full response.
        - Keep messages **short, clear, and to the point** to maintain a smooth interaction.
        - Avoid jargon or complex language; **keep it simple and easy to understand**.
        - **Emojis and informal language** can be used sparingly, but only if appropriate for the brand’s style.
        - **Break long explanations into smaller messages** to enhance readability and engagement.

  - type: 'email'
    description: |
      A **formal, asynchronous communication channel** where responses are expected to be well-structured and informative. Unlike live chat, customers expect **detailed, professional, and polished responses**.

      **Characteristics**:
        - Structured and detailed: Responses should **address all aspects** of the customer’s inquiry.
        - Professional and polite: The tone should be **respectful and courteous** at all times.
        - Time-sensitive but not immediate: Customers expect a **thorough response** rather than a quick reply.
        - Permanent record: Emails are **documented and often referenced later**, so accuracy is key.

      **Guidelines**:
        - **Use a clear subject line** summarizing the inquiry (e.g., "Re: Issue with Account Login").
        - Start with a **polite greeting** (e.g., "Dear [Customer Name], Thank you for reaching out.").
        - Provide a **structured response**, addressing the issue logically and clearly.
        - Use **correct spelling, grammar, and punctuation** to reflect credibility.
        - **Summarize next steps** or a call to action (e.g., "If you need further assistance, feel free to reply").
        - End with a **polite closing and agent signature** (e.g., "Kind regards, [Your Name]").

  - type: 'social media message'
    description: |
      A **fast, informal, and highly public** customer service channel conducted through platforms like Facebook Messenger, Instagram Direct, or Twitter DMs. Responses should be **brief, engaging, and aligned with social media norms**.

      **Characteristics**:
        - Casual and conversational: Customers expect **a friendly, approachable tone** rather than corporate formalities.
        - High-speed expectations: Customers anticipate **immediate responses**, especially on platforms like Twitter.
        - Public and private messaging: Some inquiries may need **to be moved to private messages (DMs) for security**.
        - Brand representation: Responses must **reflect the brand’s voice** while staying professional.

      **Guidelines**:
        - **Acknowledge the customer quickly**, even if a full resolution requires more time.
        - Keep responses **short and conversational**, avoiding unnecessary formality.
        - **Redirect sensitive issues to private messages** when needed (e.g., "We’d love to assist further! Please send us a DM").
        - **Use emojis sparingly**—only when appropriate for the brand’s voice.

  - type: 'SMS/Text Message'
    description: |
      A **concise, direct** form of communication where brevity is essential. Customers expect **immediate and to-the-point responses** without unnecessary detail.

      **Characteristics**:
        - Extremely short and direct: Customers expect **quick, action-oriented messages**.
        - Limited format: No rich media, formatting, or long paragraphs.
        - Urgent nature: Often used for **quick updates, confirmations, or basic support**.
        - One-on-one engagement: No public visibility, making it **more personal than social media**.

      **Guidelines**:
        - Keep messages **under 160 characters** where possible.
        - Be **direct and to the point** (e.g., "Your request has been received. Reply YES to confirm.").
        - Use **clear call-to-actions** when applicable (e.g., "Reply 1 for support, 2 for billing.").
        - Avoid unnecessary pleasantries—SMS is for **quick transactions, not long conversations**.
