company_name:
  - 'Migros Bank'
  - 'Raiffeisen Bank'
  - 'UBS'
  - 'Zürcher Kantonalbank'
  - 'Credit Suisse'
  - 'PostFinance'
  - 'Bank Cler'
  - 'Bank Coop'
  - 'Bank Thalwil'
  - 'Clientis Bank'
  - 'Glarner Kantonalbank'
  - 'Luzerner Kantonalbank'
  - 'Nidwaldner Kantonalbank'
  - 'Obwaldner Kantonalbank'
  - 'Schaffhauser Kantonalbank'
  - 'St. Galler Kantonalbank'
  - 'Thurgauer Kantonalbank'
  - 'Zuger Kantonalbank'
  - 'Basellandschaftliche Kantonalbank'
  - 'Basler Kantonalbank'
  - 'Graubündner Kantonalbank'
  - 'Schwyzer Kantonalbank'
  - 'Solothurner Kantonalbank'
  - 'Walliser Kantonalbank'
  - 'Appenzeller Kantonalbank'
  - 'Freiburger Kantonalbank'
  - 'Banque Cantonale de Genève'
  - 'Banque Cantonale Vaudoise'
  - 'Banque Cantonale Neuchâteloise'
  - 'Banque Cantonale du Jura'
  - 'Banque Cantonale du Valais'

person_name:
  - 'Anna Müller'
  - 'Benjamin Meier'
  - 'Carla Fischer'
  - 'David Schmid'
  - 'Elena Weber'
  - 'Fabian Huber'
  - 'Gina Keller'
  - 'Hans Vogt'
  - 'Iris Bader'
  - 'Jonas Graf'
  - 'Karin Roth'
  - 'Lukas Zimmermann'
  - 'Maria Koch'
  - 'Nico Schuler'
  - 'Olivia Lang'
  - 'Peter Baumann'
  - 'Quentin Schäfer'
  - 'Rita Schmid'
  - 'Simon Weber'
  - 'Tanja Meier'
  - 'Urs Fischer'
  - 'Valentina Huber'
  - 'Werner Vogt'
  - 'Xenia Bader'
  - 'Yannick Graf'
  - 'Zoe Roth'
  - 'Andrea Zimmermann'
  - 'Boris Koch'
  - 'Carmen Schuler'
  - 'Daniel Lang'
  - 'Eva Baumann'
  - 'Felix Schäfer'
  - 'Gabriela Schmid'
