topics_actionable_items:
  Nachlass & Erbschaften:
    - Unterstützung bei einer Erbschaftsangelegenheit erhalten
    - Ein Erbenkonto eröffnen und den Prozess verstehen
    - Einen Sterbefall bei der Bank melden und erforderliche Dokumente einreichen
    - Informationen zur Nachlassaufteilung und den nächsten Schritten erhalten
    - Nachlassverbindlichkeiten klären und offene Forderungen prüfen

  Konto & Zahlungsverkehr:
    - Ein neues Konto eröffnen oder ein bestehendes Konto schließen
    - Informationen zu den Konditionen und Dienstleistungen eines Bankkontos erhalten
    - Eine Überweisung ins Ausland durchführen und die Gebühren klären
    - Dauerauftrag einrichten, ändern oder kündigen
    - Probleme mit einer nicht ausgeführten Zahlung klären

  Kreditkarten & Bankkarten:
    - Eine neue Kredit- oder Debitkarte beantragen
    - Eine verlorene oder gestohlene Karte sperren lassen
    - Das Kartenlimit anpassen oder eine Zusatzkarte beantragen
    - Informationen zu Fremdwährungsgebühren und Umrechnungskursen erhalten
    - Unterstützung bei einer abgelehnten Zahlung mit der Kreditkarte erhalten

  Kredite & Finanzierung:
    - Einen Privatkredit beantragen und Konditionen besprechen
    - Eine Hypothek beantragen oder bestehende Hypothekenkonditionen anpassen
    - Eine vorzeitige Rückzahlung einer Finanzierung planen
    - Möglichkeiten zur Tragbarkeit eines Kredits überprüfen
    - Informationen zu den Voraussetzungen für eine Kreditbewilligung erhalten

  Investitionen & Vorsorge:
    - Ein Depot eröffnen und Informationen zu Anlagestrategien erhalten
    - In Wertschriften investieren und aktuelle Marktinformationen abrufen
    - Ein Vorsorgekonto eröffnen und die steuerlichen Vorteile verstehen
    - Informationen zu Fondssparplänen und Anlagemöglichkeiten erhalten
    - Eine Risikoeinschätzung für eine geplante Investition durchführen

  Betrugsfälle & Sicherheit:
    - Verdächtige Aktivitäten oder einen Betrugsfall melden
    - Unterstützung bei der Rückerstattung einer betrügerischen Transaktion anfordern
    - Informationen zu Schutzmaßnahmen gegen Online-Betrug erhalten
    - Eine missbräuchliche Nutzung der Bankkarte oder des Online-Bankings klären
    - Sicherheitsmaßnahmen für kontaktlose Zahlungen und Online-Shopping optimieren

  Steuerliche & rechtliche Themen:
    - Informationen zu den AIA-/FATCA-Meldepflichten erhalten
    - Eine Steuerbescheinigung oder eine Stichtagsbescheinigung anfordern
    - Erbschaftssteuerfragen klären und rechtliche Vorgaben verstehen
    - Gerichtliche Verfügungen einreichen oder Informationen dazu erhalten
    - Beratung zur Entbindung vom Bankkundengeheimnis anfordern

  Geschäftskunden & Unternehmensfinanzierung:
    - Ein Firmenkonto eröffnen und verfügbare Dienstleistungen prüfen
    - Finanzierungsmöglichkeiten für ein Unternehmen besprechen
    - Eine Bankgarantie beantragen und die Voraussetzungen klären
    - Ein Kapitaleinzahlungskonto für die Unternehmensgründung eröffnen
    - Ein Leasingangebot für geschäftliche Zwecke erhalten

  Digitale Bankdienstleistungen:
    - Unterstützung bei Problemen mit dem E-Banking-Zugang erhalten
    - Eine eBill-Verknüpfung einrichten oder eine bestehende ändern
    - QR-Rechnungen erstellen oder Zahlungen mit QR-Codes abwickeln
    - Unterstützung bei der Nutzung mobiler Zahlungsmethoden wie Apple Pay oder TWINT erhalten
    - Sicherheitsoptionen für den Online-Banking-Zugang optimieren
