topics_actionable_items:
  Estate & Inheritance:
    - Get support for an inheritance matter
    - Open an heir account and understand the process
    - Report a death to the bank and submit required documents
    - Receive information on estate distribution and next steps
    - Clarify estate liabilities and review outstanding claims

  Accounts & Payments:
    - Open a new account or close an existing one
    - Obtain information on account conditions and banking services
    - Make an international transfer and clarify associated fees
    - Set up, modify, or cancel a standing order
    - Resolve issues with a failed payment

  Credit Cards & Bank Cards:
    - Apply for a new credit or debit card
    - Block a lost or stolen card
    - Adjust the card limit or request an additional card
    - Get information on foreign currency fees and exchange rates
    - Receive support for a declined credit card transaction

  Loans & Financing:
    - Apply for a personal loan and discuss conditions
    - Apply for a mortgage or adjust existing mortgage terms
    - Plan an early repayment of a loan
    - Check the affordability of a loan
    - Obtain information on the requirements for loan approval

  Investments & Retirement Planning:
    - Open a securities account and receive investment strategy guidance
    - Invest in securities and access current market information
    - Open a retirement savings account and understand tax benefits
    - Get information on mutual fund savings plans and investment opportunities
    - Conduct a risk assessment for a planned investment

  Fraud Cases & Security:
    - Report suspicious activity or a fraud case
    - Request support for the refund of a fraudulent transaction
    - Obtain information on protective measures against online fraud
    - Address unauthorized use of a bank card or online banking account
    - Optimize security measures for contactless payments and online shopping

  Tax & Legal Matters:
    - Obtain information on AIA/FATCA reporting obligations
    - Request a tax certificate or a balance statement as of a specific date
    - Clarify inheritance tax issues and understand legal requirements
    - Submit court orders or request information about them
    - Seek advice on releasing bank secrecy obligations

  Business Clients & Corporate Financing:
    - Open a business account and review available services
    - Discuss financing options for a company
    - Apply for a bank guarantee and clarify the requirements
    - Open a capital deposit account for business formation
    - Obtain a leasing offer for business purposes

  Digital Banking Services:
    - Get support for issues with e-banking access
    - Set up or modify an eBill connection
    - Create QR invoices or process payments using QR codes
    - Receive assistance with mobile payment methods such as Apple Pay or TWINT
    - Optimize security settings for online banking access
